openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
paths:
  /books:
    get:
      summary: Retrieves a list of books
      responses:
        '200':
          description: A JSON array of book names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    author:
                      type: string
  /books/{bookId}:
    get:
      summary: Retrieves a book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          description: The ID of the book to retrieve
          schema:
            type: integer
          style: simple
      responses:
        '200':
          description: A JSON object of the book
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string