"""empty message

Revision ID: 92857c36b570
Revises: 
Create Date: 2024-04-20 20:39:25.503158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92857c36b570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ParentCategoryID', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=150), nullable=False),
    sa.Column('Description', sa.String(length=10000), nullable=False),
    sa.Column('ImageURL', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('device', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(length=80), nullable=False),
    sa.Column('loginType', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('Barcode', sa.String(length=80), nullable=False),
    sa.Column('sellerEmail', sa.String(length=120), nullable=False),
    sa.Column('Condition', sa.String(length=80), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('DateListed', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Dimensions', sa.String(length=100), nullable=True),
    sa.Column('Weight', sa.String(length=80), nullable=True),
    sa.Column('Manufacturer', sa.String(length=80), nullable=True),
    sa.Column('ViewsCount', sa.Integer(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('IsFeatured', sa.Boolean(), nullable=True),
    sa.Column('SellerNotes', sa.String(length=1000), nullable=True),
    sa.Column('Tags', sa.String(length=1000), nullable=True),
    sa.Column('CustomerRatingAverage', sa.Float(), nullable=True),
    sa.Column('NumberOfReviews', sa.Integer(), nullable=True),
    sa.Column('SEOKeywords', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('Img', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('VideoFilePath', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_videos')
    op.drop_table('product_img')
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('login_times')
    op.drop_table('category')
    # ### end Alembic commands ###
